### ISSUE TITLE
Insert getter/setter does not take typed properties into account

### ISSUE THREAD

**Issue by emilnymann** [r4ven1245/vscode-php-getter-setter#2] opened 2021-07-05 16:20 UTC
When adding getters and setters for a class property, typed properties are not taken into account. They are added, but the getter return type and the setter argument are not typed.

Example given:
Take the class property _website_, typed as a nullable string.
![image](https://user-images.githubusercontent.com/27289912/124498786-39033100-ddbd-11eb-8a93-db7ec937f7a8.png)

Use the _Add PHP 8 Getter and Setter_ command and the resulting functions look like this...
![image](https://user-images.githubusercontent.com/27289912/124498842-5637ff80-ddbd-11eb-86f2-361d1562cbdc.png)

... where they should preferably look like this.
![image](https://user-images.githubusercontent.com/27289912/124498935-7798eb80-ddbd-11eb-8363-cdbec7618a09.png)

I realise it's not a jarring issue, but it takes away from the otherwise huge workflow improvement of this extension.

**Comment by r4ven1245** [comment] 2021-07-06 10:16
The extension does account for typed properties, in fact that's the only reason I forked it in the first place
The issue is that the line reader is incompatible with your multiple spaces formatting, fixing it right now

**Comment by emilnymann** [comment] 2021-07-06 10:40
I see, thanks!

**Comment by r4ven1245** [comment] 2021-07-06 13:48
Fixed in release 1.1.1

**Closed by r4ven1245** 2021-07-06 13:48 UTC
Labels: bug

**Comment by ayoub-elkhadir-d** [comment] 2026-01-08 15:07
good
